-- ============================================================================
-- Migration: Create food_items table (individual food entries)
-- Reference data — publicly readable, admin-writable only.
-- Run in: Supabase SQL Editor (Dashboard → SQL Editor → New Query)
-- ============================================================================

-- 1. Create the food_items table
CREATE TABLE IF NOT EXISTS public.food_items (
    food_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_code VARCHAR NOT NULL,
    food_name VARCHAR NOT NULL,
    major_group_id BIGINT NOT NULL REFERENCES public.major_groups(major_group_id)
);

-- 2. Index on major_group_id for joins
CREATE INDEX IF NOT EXISTS idx_food_items_major_group_id
    ON public.food_items(major_group_id);

-- 3. pg_trgm GIN index on food_name for fast ILIKE searches
CREATE INDEX IF NOT EXISTS idx_food_items_food_name_trgm
    ON public.food_items USING GIN (food_name gin_trgm_ops);

-- 4. Enable Row Level Security
ALTER TABLE public.food_items ENABLE ROW LEVEL SECURITY;

-- 5. RLS Policy: Everyone can read food items
CREATE POLICY "Anyone can read food items"
    ON public.food_items
    FOR SELECT
    USING (true);

-- 6. Grant read access to all roles
GRANT SELECT ON public.food_items TO authenticated;
GRANT SELECT ON public.food_items TO anon;

