-- ============================================================================
-- Migration: Create food_nutrient_values table (per-food nutrient amounts)
-- Reference data — publicly readable, admin-writable only.
-- Run in: Supabase SQL Editor (Dashboard → SQL Editor → New Query)
-- ============================================================================

-- 1. Create the food_nutrient_values table
CREATE TABLE IF NOT EXISTS public.food_nutrient_values (
    food_nutrient_value_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_id BIGINT NOT NULL REFERENCES public.food_items(food_id),
    nutrient_id BIGINT NOT NULL REFERENCES public.nutrient_definitions(nutrient_id),
    value NUMERIC NOT NULL
);

-- 2. Indexes for fast joins
CREATE INDEX IF NOT EXISTS idx_food_nutrient_values_food_id
    ON public.food_nutrient_values(food_id);

CREATE INDEX IF NOT EXISTS idx_food_nutrient_values_nutrient_id
    ON public.food_nutrient_values(nutrient_id);

-- 3. Unique constraint: one value per food + nutrient combination
CREATE UNIQUE INDEX IF NOT EXISTS idx_food_nutrient_values_food_nutrient
    ON public.food_nutrient_values(food_id, nutrient_id);

-- 4. Enable Row Level Security
ALTER TABLE public.food_nutrient_values ENABLE ROW LEVEL SECURITY;

-- 5. RLS Policy: Everyone can read nutrient values
CREATE POLICY "Anyone can read food nutrient values"
    ON public.food_nutrient_values
    FOR SELECT
    USING (true);

-- 6. Grant read access to all roles
GRANT SELECT ON public.food_nutrient_values TO authenticated;
GRANT SELECT ON public.food_nutrient_values TO anon;

